# Makefile automatically generated by ghdl
# Version: GHDL 2.0.0 (Debian 2.0.0+dfsg-6.2) [Dunoon edition] - llvm code generator
# Command used to generate this makefile:
# /usr/bin/ghdl-llvm --gen-makefile --ieee=synopsys -fexplicit --workdir=WORK testbench

GHDL=/usr/bin/ghdl-llvm
GHDLFLAGS= --ieee=synopsys -fexplicit --workdir=WORK

# Default target
all: testbench

# Elaboration target
testbench: /usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_1164.o /usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_1164-body.o /usr/lib/ghdl/llvm/vhdl/ieee/v93/numeric_std.o /usr/lib/ghdl/llvm/vhdl/ieee/v93/numeric_std-body.o WORK/gbdt_test.o /usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_arith.o /usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_unsigned.o WORK/GBDT_incompleto.o WORK/reg.o WORK/memoriaROM_128x16.o WORK/mux.o
	$(GHDL) -e $(GHDLFLAGS) $@

# Run target
run: testbench
	$(GHDL) -r testbench $(GHDLRUNFLAGS)

# Targets to analyze files
/usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_1164.o: /usr/lib/ghdl/llvm/vhdl/ieee/v93/../../src/ieee/v93/std_logic_1164.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
/usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_1164-body.o: /usr/lib/ghdl/llvm/vhdl/ieee/v93/../../src/ieee/v93/std_logic_1164-body.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
/usr/lib/ghdl/llvm/vhdl/ieee/v93/numeric_std.o: /usr/lib/ghdl/llvm/vhdl/ieee/v93/../../src/ieee/v93/numeric_std.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
/usr/lib/ghdl/llvm/vhdl/ieee/v93/numeric_std-body.o: /usr/lib/ghdl/llvm/vhdl/ieee/v93/../../src/ieee/v93/numeric_std-body.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
WORK/gbdt_test.o: gbdt_test.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
/usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_arith.o: /usr/lib/ghdl/llvm/vhdl/ieee/v93/../../src/synopsys/std_logic_arith.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
/usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_unsigned.o: /usr/lib/ghdl/llvm/vhdl/ieee/v93/../../src/synopsys/std_logic_unsigned.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
WORK/GBDT_incompleto.o: GBDT_incompleto.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/reg.o: reg.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/memoriaROM_128x16.o: memoriaROM_128x16.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/mux.o: mux.vhd
	$(GHDL) -a $(GHDLFLAGS) $<

# Files dependences
/usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_1164.o: 
/usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_1164-body.o:  /usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_1164.o
/usr/lib/ghdl/llvm/vhdl/ieee/v93/numeric_std.o:  /usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_1164.o
/usr/lib/ghdl/llvm/vhdl/ieee/v93/numeric_std-body.o:  /usr/lib/ghdl/llvm/vhdl/ieee/v93/numeric_std.o
WORK/gbdt_test.o:  /usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_1164.o /usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_1164-body.o /usr/lib/ghdl/llvm/vhdl/ieee/v93/numeric_std.o /usr/lib/ghdl/llvm/vhdl/ieee/v93/numeric_std-body.o
/usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_arith.o:  /usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_1164.o
/usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_unsigned.o:  /usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_1164.o /usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_arith.o
WORK/GBDT_incompleto.o:  /usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_1164.o /usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_arith.o /usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_unsigned.o /usr/lib/ghdl/llvm/vhdl/ieee/v93/numeric_std.o
WORK/reg.o:  /usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_1164.o
WORK/memoriaROM_128x16.o:  /usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_1164.o /usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_unsigned.o /usr/lib/ghdl/llvm/vhdl/ieee/v93/numeric_std.o
WORK/mux.o:  /usr/lib/ghdl/llvm/vhdl/ieee/v93/std_logic_1164.o /usr/lib/ghdl/llvm/vhdl/ieee/v93/numeric_std.o
